# Site settings
title: Bastion Fennell
email: bastionfennell@thefrontside.net
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. It's a collection of things I find interesting,
  from programming to dancing
baseurl: "/bastions-musings" # the subpath of your site, e.g. /blog/
url: "http://bastionfennell.com" # the base hostname & protocol for your site
twitter_username: snowyrat
github_username:  snowyrat

# Build settings
markdown: kramdown
